#!/usr/bin/env bash
# This is the comment
for i in "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School"; do
	echo $i;
done
