#!/usr/bin/env bash
# file 12-tell_the_story_of_passwd

while IFS=':' read -r one two three four five six seven
do
	echo "The user $one is part of the $four gang, lives in $six and rides $seven. $three's place is protected by the passcode $two, more info about the user here: $five"
done < /etc/passwd
