#!/usr/bin/env bash
# This is the comment

i=1

while [ $i -lt 21 ]; do
	if [ $i == 4 ]
	then
		echo "$i"
		echo "bad luck from China"
	elif [ $i == 9 ]; then
		echo "$i"
		echo "bad luck from Japan"
	elif [ $i == 17 ]; then
		echo "$i"
		echo "good luck from Italy"
	else
		echo "$i"
	fi

	((i++))
done
